on:
  workflow_dispatch
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: io.github.quincycheng.SD_BlueDucky
        manifest-path: io.github.quincycheng.SD_BlueDucky.yml
        cache-key: flatpak-builder-${{ github.sha }}
